### ISSUE TITLE
Crashes with 0.98.2

### ISSUE THREAD

**Issue by leedave** [LTVA1/flipper-zero-video-player#10]
Just tried it with the new release. Unfortunately the device crashes with 
**furi_check failed**
as soon as you start a video.

**Comment by LTVA1** [comment]
I have just updated it with some fixes 10 hours ago, please try again. If still crashes, please download latest Unleashed firmware `e` version, and grab fap file from there.

**Comment by LTVA1** [comment]
I have just checked for Unleashed 071 version, works just fine

**Comment by LTVA1** [comment]
https://github.com/LTVA1/flipper-zero-video-player/releases/tag/v0.1 please try this fap

**Comment by leedave** [comment]
Great work, runs again without problems in 0.98.2, you rock!
