### ISSUE TITLE
script errors

### ISSUE THREAD

**Issue by qqmajikpp** [LTVA1/flipper-zero-video-player#2]
the scrippt says it runs successfully but im not finding and bundle files and iit also says
Unhandled exception thrown: read access violation.
dirp was nullptr.

**Comment by qqmajikpp** [comment]
![image](https://user-images.githubusercontent.com/84942886/224658031-cf5dc606-b833-490f-a6f8-031325286069.png)

**Comment by LTVA1** [comment]
Have you assigned a correct path in #define in cpp file? The path should lead to the folder where your wav file and frames folder are

**Comment by LTVA1** [comment]
You also have to do all the stuff in the folder where you don't need admin privileges to write files. E.g. some folder on your desktop.

**Comment by LTVA1** [comment]
Show me the #define section and the folder contents, please

**Comment by qqmajikpp** [comment]
USER SETTINGS:

#define FOLDER_PATH "D:\Code\faps\flipper-zero-video-player-main\ffmpg\animaniacs"
#define SAMPLE_RATE 44100
#define FPS 24
#define HEIGHT 64
#define WIDTH 128 /*width of your video, determined by ffmpeg. Here it is for 4:3 aspect ratio*/
![image](https://user-images.githubusercontent.com/84942886/224716221-9d8e6dcb-392f-4bf6-a581-8dee2355bb12.png)

**Comment by qqmajikpp** [comment]
tried  putting iit in documents and removing the vido. still no diice

**Comment by LTVA1** [comment]
Don't recommend 24 fps with such sample rate, the sound will be out of sync. See updated repository readme. Change all the `\` to `/`. Also do your bmp files in frames folder have 128x64 resolution as well?

**Comment by qqmajikpp** [comment]
example frame produced by following the readme

**Comment by qqmajikpp** [comment]
![image](https://user-images.githubusercontent.com/84942886/224719589-f72d8347-a2d9-4225-99aa-f09c5a126398.png)

**Comment by LTVA1** [comment]
As far as I see it is not 128x64. Edit your ffmpeg commands or change the defines. You need to keep the same image size in first ffmpeg command and in define in cpp file

**Comment by qqmajikpp** [comment]
yeah..... this is apparently too convoluted for me
