### ISSUE TITLE
can't obtain bundle.bnd at the end...

### ISSUE THREAD

**Issue by AxxlZero** [LTVA1/flipper-zero-video-player#3]
HI LTVA1,

first thanks for this video player ! Great idea !

So, sorry to disturb.....I'm almost done with your video player but got a problem 

I'm succesfull in obtaining the frames and extarcting audio with ffmpeg...
I can open the visual studio project, no problem, but when I generate the result I obtain a "flipper_video_converter.exe" file.
This file when I run it seems to do nothing and when I read it withe notepad+ I see a lot of strange symbols, this file seems corrupted !?! 
And it don't generate a bundle.bnd file...   I'm failing something but don't see what... :-(

Sorry for bad english, I'm from France.....and also, trying my best in understanding python, C etc....really new to this !
Thanks if you have 5 minutes to answer and guide me....
Bests regards, Alex.

**Comment by LTVA1** [comment]
You need to open the project in Visual Studio and run it in Visual Studio. I don't know how it manages to generate an exe file in the folder where it should make .bnd one

**Comment by AxxlZero** [comment]
ok, thank you to took time to answer me...
