### ISSUE TITLE
Does not run on latest firmware

### ISSUE THREAD

**Issue by supercreate01** [LTVA1/flipper-zero-video-player#5]
I can compile the app fine, but it will not run on the latest firmware version, 86.1

**Comment by LTVA1** [comment]
Damn, I had similar issue with flizzer tracker. Will check and try to fix soon

**Comment by LTVA1** [comment]
It works on latest Unleashed release hmmm. Need to test on OFW release then

**Comment by LTVA1** [comment]
I checked on latest dev OFW commit, it works. Please check if you have most recent video player source code version, that's most likely the reason why it does not run for you.

**Comment by supercreate01** [comment]
Thank you.
