### ISSUE TITLE
follow device silence mode

### ISSUE THREAD

**Issue by blaineam** [LTVA1/flipper-zero-video-player#7]
It would be nice if the video player followed the device silent mode so that if it is in silent mode, the videos do not play sound and if the flipper zero is not in silent mode the video player allows audio to be played.

**Comment by LTVA1** [comment]
Hmm I will search for the function that tells you if debice is in silent mode

**Comment by blaineam** [comment]
alternative option would maybe be to use the up and down arrows to control volume or maybe have one be a mute toggle if volume control is tricky. I wasnt able to find how to tie into the silent (stealth) mode either.

**Comment by LTVA1** [comment]
Yeah I think it has enough power to multiply by volume

**Comment by LTVA1** [comment]
Okay soon when I remember how to format the code I will push the commit that makes it silent

**Comment by LTVA1** [comment]
Yes, now it should obey stealth mode

**Comment by blaineam** [comment]
it works thanks!
